import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Container from "@mui/material/Container";
import {
  Typography,
  Box,
  Grid,
  Paper,
  Stack,
  Button,
  Drawer,
  AppBar,
  Toolbar,
  // makeStyles,
} from "@mui/material";

import { makeStyles } from "@mui/styles";
import MainContent from "../Components/MainComponent/MainContent";
import ModalComponent from "../Components/Modal.jsx/ModalComponent";
import { Formik } from "formik";
import { useState } from "react";
import ViewModal from "../Components/ViewModal/ViewModal";

const inter = Inter({ subsets: ["latin"] });
const drawerWidth = 240;

export default function Home() {
  const classes = useStyles();
  const [open, setOpen] = useState(false);
  const [formValues, setFormValues] = useState([]);
  const [subTask, setsubTask] = useState([]);

  // console.log(formValues);
  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="xl" sx={{ overflowX: "none" }}>
        <AppBar position="fixed" sx={{ background: "#2c2c38" }}>
          <Toolbar>
            <Stack
              direction="row"
              justifyContent="space-between"
              sx={{ width: "100%" }}
            >
              <Typography variant="h4">Platform</Typography>
              <Box>
                <Button
                  variant="contained"
                  sx={{
                    background: "#6360c7",
                    borderRadius: "2rem",
                    textTransform: "capitalize",
                    fontWeight: 400,
                  }}
                  onClick={() => {
                    setOpen(true);
                  }}
                  //  startIcon={}
                >
                  Add New Task
                </Button>
              </Box>
            </Stack>
          </Toolbar>
        </AppBar>

        <div className={classes.root}>
          {/* <Drawer
            className={classes.drawer}
            variant="permanent"
            anchor="left"
            classes={{ paper: classes.drawerPaper }}
          >
            hello
          </Drawer> */}

          <MainContent formValues={formValues} subTask={subTask} />
        </div>

        <Formik
          initialValues={{
            title: "",
            description: "",
            status: "",
            subtasks: [""],
          }}
          onSubmit={(values, onSubmitProps) => {
            setFormValues([...formValues, values]);
            setOpen(false);
            onSubmitProps.resetForm();
          }}
        >
          {({ values }) => (
            <ModalComponent
              open={open}
              setOpen={setOpen}
              props={values}
              subTask={subTask}
              setsubTask={setsubTask}
            />
          )}
        </Formik>
      </Container>
    </>
  );
}

const useStyles = makeStyles({
  drawer: {
    width: drawerWidth,
  },
  drawerPaper: {
    width: drawerWidth,
    background: "#2c2c38",
  },
  root: {
    display: "flex",
  },
});
